import { tesla1, tesla2, tesla3, tesla4 } from "@/public";

export const cardDetails = [
  {
    image: tesla1,
    name: "Tesla model s",
    date: "2022",
    model: "Automatic",
    type: "Electric",
    miles: "440miles",
  },
  {
    image: tesla2,
    name: "Tesla model s",
    date: "2022",
    model: "Automatic",
    type: "Electric",
    miles: "440miles",
  },
  {
    image: tesla3,
    name: "Tesla model s",
    date: "2022",
    model: "Automatic",
    type: "Electric",
    miles: "440miles",
  },
  {
    image: tesla4,
    name: "Tesla model s",
    date: "2022",
    model: "Automatic",
    type: "Electric",
    miles: "440miles",
  },
  {
    image: tesla1,
    name: "Tesla model s",
    date: "2022",
    model: "Automatic",
    type: "Electric",
    miles: "440miles",
  },
  {
    image: tesla2,
    name: "Tesla model s",
    date: "2022",
    model: "Automatic",
    type: "Electric",
    miles: "440miles",
  },
  {
    image: tesla3,
    name: "Tesla model s",
    date: "2022",
    model: "Automatic",
    type: "Electric",
    miles: "440miles",
  },
  {
    image: tesla4,
    name: "Tesla model s",
    date: "2022",
    model: "Automatic",
    type: "Electric",
    miles: "440miles",
  },
];
